# Generated by Django 5.2.8 on 2025-11-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotatedimage",
            name="annotated_file",
            field=models.ImageField(
                blank=True, null=True, upload_to="annotated_output/"
            ),
        ),
        migrations.AddField(
            model_name="annotatedimage",
            name="mask_file",
            field=models.ImageField(blank=True, null=True, upload_to="masks/"),
        ),
    ]
